# Generated by Django 3.2 on 2021-04-29 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210429_1914"),
        ("stories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("ffd6c534-f269-4e66-8771-6e2a93b013fc"), unique=True
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("55c09412-a4d1-4c31-b3bc-df695ed7ba06"), unique=True
            ),
        ),
        migrations.AddField(
            model_name="storycomponent",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("ed8a66b0-5df5-4e5b-b200-1e4447ac5102"), unique=True
            ),
        ),
        migrations.AddField(
            model_name="storycomponentfiles",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("fa1cea89-8784-44c4-9f34-d545b891d5cc"), unique=True
            ),
        ),
        migrations.AddField(
            model_name="storycomponentpictures",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("65113455-70ad-4743-b7ff-2c6c5235c433"), unique=True
            ),
        ),
        migrations.AddField(
            model_name="storylocations",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("61f0d26d-3101-4291-a010-18c4b4ad9f90"), unique=True
            ),
        ),
        migrations.AddField(
            model_name="storytags",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("b8ba2fd6-9c0a-4a5f-9bea-392482d8f253"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="users.profile",
            ),
        ),
    ]
