# Generated by Django 3.2 on 2021-06-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_alter_storylocations_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycomponent',
            name='type',
            field=models.CharField(blank=True, choices=[('TEXT', 'TEXT'), ('TITLE', 'TITLE'), ('IMAGE_URL', 'IMAGE_URL'), ('IMAGE', 'IMAGE')], db_index=True, max_length=100, null=True),
        ),
    ]
