# Generated by Django 3.2 on 2021-06-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_generictoken_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followed_authors',
            field=models.ManyToManyField(related_name='followed_by', to='users.Profile'),
        ),
    ]
