# Generated by Django 3.2 on 2021-06-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storynotification",
            name="notification_ptr",
        ),
        migrations.RemoveField(
            model_name="storynotification",
            name="story",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="created",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="modified",
        ),
        migrations.DeleteModel(
            name="CommentNotification",
        ),
        migrations.DeleteModel(
            name="StoryNotification",
        ),
    ]
