# Generated by Django 3.2 on 2021-06-15 14:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_basenotification_followed_id_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenotification',
            name='followed_id_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
